version: "3.5"

services:
  php_fpm:
      build: .
      container_name: co2_php_fpm
      restart: always
      working_dir: /usr/share/nginx/CO2-footprint
      networks:
          - co2
      volumes:
          - ./:/usr/share/nginx/CO2-footprint
          - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      extra_hosts:
          - "co2.today:${CO2_NGINX_HOST}"

  nginx:
      image: nginx:1.15
      container_name: co2_nginx
      restart: always
      working_dir: /usr/share/nginx/CO2-footprint
      networks:
          - co2
      ports:
          - "80:80"
      volumes:
          - ./:/usr/share/nginx/CO2-footprint
          - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
          - ./docker/nginx/ssl/co2.today.crt:/etc/nginx/ssl/co2.today.crt
          - ./docker/nginx/ssl/co2.today.key:/etc/nginx/ssl/co2.today.key

  mysql:
      image: mysql:5.7
      container_name: co2_mysql
      restart: always
      networks:
          - co2
      volumes:
          - ./docker/mysql/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
          - ./docker/mysql/database.sql:/home/database.sql
      ports:
          - "3306:3306"
      environment:
          - MYSQL_DATABASE=${DB_DATABASE}
          - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
          - MYSQL_USER=${DB_USERNAME}
          - MYSQL_PASSWORD=${DB_PASSWORD}

networks:
  co2:
    driver: bridge
