server {
    listen 443 ssl;
    server_name             api.co2.today;
    ssl_certificate         /etc/nginx/ssl/co2.today.crt;
    ssl_certificate_key     /etc/nginx/ssl/co2.today.key;
    ssl_ciphers             EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH;
    ssl_protocols           TLSv1.1 TLSv1.2;

    root /usr/share/nginx/CO2-footprint/api;

    client_max_body_size 20M;

    location / {
        try_files $uri $uri/index.php;
    }

    location ~ ^/.+\.php(/|$) {
        fastcgi_pass php_fpm:9000;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}

server {
    listen 443 ssl;
    server_name             co2.today;
    ssl_certificate         /etc/nginx/ssl/co2.today.crt;
    ssl_certificate_key     /etc/nginx/ssl/co2.today.key;
    ssl_ciphers             EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH;
    ssl_protocols           TLSv1.1 TLSv1.2;

    root /usr/share/nginx/CO2-footprint/build;

    client_max_body_size 20M;

    location / {
        try_files $uri $uri/index.html;
    }

    location ~ ^/.+\.php(/|$) {
        fastcgi_pass php_fpm:9000;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}
