DROP DATABASE IF EXISTS co2;

CREATE DATABASE IF NOT EXISTS co2;

USE co2;

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER, LOCK TABLES, CREATE TEMPORARY TABLES
ON co2.* TO 'root'@'localhost' IDENTIFIED BY 'password';
